name: Pack and Publish HealthTracker.Common NuGet Package

on:
  push:
    paths:
      - 'HealthTracker.Common/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: pack and push
        run: |
          cd HealthTracker.Common/HealthTracker.Common
          dotnet pack -c Release
          dotnet nuget push bin/Release/**.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate

